default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

maps: &maps
  map_tiles_provider: <%= ENV['MAP_TILES_PROVIDER'] %>
  map_tiles_provider_attribution: <%= ENV['MAP_TILES_PROVIDER_ATTRIBUTION'] %>

apis: &apis
  census_api_end_point: <%= ENV['CENSUS_API_END_POINT'] %>
  census_api_institution_code: <%= ENV['CENSUS_API_INSTITUTION_CODE'] %>
  census_api_portal_name: <%= ENV['CENSUS_API_PORTAL_NAME'] %>
  census_api_user_code: <%= ENV['CENSUS_API_USER_CODE'] %>
  sms_end_point: <%= ENV['SMS_END_POINT'] %>
  sms_username: <%= ENV['SMS_USERNAME'] %>
  sms_password: <%= ENV['SMS_PASSWORD'] %>

http_basic_auth: &http_basic_auth
  http_basic_auth: true

development:
  http_basic_username: <%= ENV['HTTP_BASIC_USERNAME'] %>
  http_basic_password: <%= ENV['HTTP_BASIC_PASSWORD'] %>
  <<: *default
  <<: *maps

test:
  <<: *default
  <<: *maps

staging:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  server_name: <%= ENV['SERVER_NAME'] %>
  rollbar_server_token: <%= ENV['ROLLBAR_SERVER_TOKEN'] %>
  http_basic_username: <%= ENV['HTTP_BASIC_USERNAME'] %>
  http_basic_password: <%= ENV['HTTP_BASIC_PASSWORD'] %>
  managers_url: <%= ENV['MANAGERS_URL'] %>
  managers_application_key: <%= ENV['MANAGERS_APPLICATION_KEY'] %>
  <<: *default
  <<: *maps
  <<: *apis

preproduction:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  server_name: <%= ENV['SERVER_NAME'] %>
  rollbar_server_token: <%= ENV['ROLLBAR_SERVER_TOKEN'] %>
  http_basic_username: <%= ENV['HTTP_BASIC_USERNAME'] %>
  http_basic_password: <%= ENV['HTTP_BASIC_PASSWORD'] %>
  managers_url: <%= ENV['MANAGERS_URL'] %>
  managers_application_key: <%= ENV['MANAGERS_APPLICATION_KEY'] %>
  twitter_key: <%= ENV['TWITTER_KEY'] %>
  twitter_secret: <%= ENV['TWITTER_SECRET'] %>
  facebook_key: <%= ENV['FACEBOOK_KEY'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  google_oauth2_key: <%= ENV['GOOGLE_OAUTH2_KEY'] %>
  google_oauth2_secret: <%= ENV['GOOGLE_OAUTH2_SECRET'] %>
  <<: *maps
  <<: *apis

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  server_name: <%= ENV['SERVER_NAME'] %>
  rollbar_server_token: <%= ENV['ROLLBAR_SERVER_TOKEN'] %>
  http_basic_username: <%= ENV['HTTP_BASIC_USERNAME'] %>
  http_basic_password: <%= ENV['HTTP_BASIC_PASSWORD'] %>
  managers_url: <%= ENV['MANAGERS_URL'] %>
  managers_application_key: <%= ENV['MANAGERS_APPLICATION_KEY'] %>
  twitter_key: <%= ENV['TWITTER_KEY'] %>
  twitter_secret: <%= ENV['TWITTER_SECRET'] %>
  facebook_key: <%= ENV['FACEBOOK_KEY'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  google_oauth2_key: <%= ENV['GOOGLE_OAUTH2_KEY'] %>
  google_oauth2_secret: <%= ENV['GOOGLE_OAUTH2_SECRET'] %>
  <<: *maps
  <<: *apis
